//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace EveLocalChatAnalyser.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ActiveProfile : ApplicationSettingsBase {
        
        private static ActiveProfile defaultInstance = ((ActiveProfile)(Synchronized(new ActiveProfile())));
        
        public static ActiveProfile Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool IsHidingBlues {
            get {
                return ((bool)(this["IsHidingBlues"]));
            }
            set {
                this["IsHidingBlues"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string VCode {
            get {
                return ((string)(this["VCode"]));
            }
            set {
                this["VCode"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-1")]
        public long KeyId {
            get {
                return ((long)(this["KeyId"]));
            }
            set {
                this["KeyId"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool IsShowingFaction {
            get {
                return ((bool)(this["IsShowingFaction"]));
            }
            set {
                this["IsShowingFaction"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool IsShowingAmarr {
            get {
                return ((bool)(this["IsShowingAmarr"]));
            }
            set {
                this["IsShowingAmarr"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool IsShowingCaldari {
            get {
                return ((bool)(this["IsShowingCaldari"]));
            }
            set {
                this["IsShowingCaldari"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool IsShowingGallente {
            get {
                return ((bool)(this["IsShowingGallente"]));
            }
            set {
                this["IsShowingGallente"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool IsShowingMinmatar {
            get {
                return ((bool)(this["IsShowingMinmatar"]));
            }
            set {
                this["IsShowingMinmatar"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public Hashtable Standings {
            get {
                return ((Hashtable)(this["Standings"]));
            }
            set {
                this["Standings"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string CharacterId {
            get {
                return ((string)(this["CharacterId"]));
            }
            set {
                this["CharacterId"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public DateTime StandingsCachedUntil {
            get {
                return ((DateTime)(this["StandingsCachedUntil"]));
            }
            set {
                this["StandingsCachedUntil"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string CharactersToActivateProfileFor {
            get {
                return ((string)(this["CharactersToActivateProfileFor"]));
            }
            set {
                this["CharactersToActivateProfileFor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-1")]
        public long LastUpdateKeyId {
            get {
                return ((long)(this["LastUpdateKeyId"]));
            }
            set {
                this["LastUpdateKeyId"] = value;
            }
        }
    }
}
