//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveLocalChatAnalyser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUsingKosInformation {
            get {
                return ((bool)(this["IsUsingKosInformation"]));
            }
            set {
                this["IsUsingKosInformation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsShowingExitedCharacters {
            get {
                return ((bool)(this["IsShowingExitedCharacters"]));
            }
            set {
                this["IsShowingExitedCharacters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("430, 220")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point WindowPosition {
            get {
                return ((global::System.Drawing.Point)(this["WindowPosition"]));
            }
            set {
                this["WindowPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsDrawingBackgroundDependingOnStatus {
            get {
                return ((bool)(this["IsDrawingBackgroundDependingOnStatus"]));
            }
            set {
                this["IsDrawingBackgroundDependingOnStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BetaEveKill")]
        public string ExternalService {
            get {
                return ((string)(this["ExternalService"]));
            }
            set {
                this["ExternalService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUsingKillboardAnalysis {
            get {
                return ((bool)(this["IsUsingKillboardAnalysis"]));
            }
            set {
                this["IsUsingKillboardAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideNews0 {
            get {
                return ((bool)(this["HideNews0"]));
            }
            set {
                this["HideNews0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double FontSize {
            get {
                return ((double)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideNews1 {
            get {
                return ((bool)(this["HideNews1"]));
            }
            set {
                this["HideNews1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NewsVersionToHide {
            get {
                return ((int)(this["NewsVersionToHide"]));
            }
            set {
                this["NewsVersionToHide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsShowingSecurityStatus {
            get {
                return ((bool)(this["IsShowingSecurityStatus"]));
            }
            set {
                this["IsShowingSecurityStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MessageOfTheDayNumber {
            get {
                return ((int)(this["MessageOfTheDayNumber"]));
            }
            set {
                this["MessageOfTheDayNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string ActiveProfile {
            get {
                return ((string)(this["ActiveProfile"]));
            }
            set {
                this["ActiveProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"Name\":\"Default\", \"Settings\":{}}]")]
        public string ProfilesSerialized {
            get {
                return ((string)(this["ProfilesSerialized"]));
            }
            set {
                this["ProfilesSerialized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSwitchingActiveProfileAutomatically {
            get {
                return ((bool)(this["IsSwitchingActiveProfileAutomatically"]));
            }
            set {
                this["IsSwitchingActiveProfileAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[]")]
        public string CoalitionsJson {
            get {
                return ((string)(this["CoalitionsJson"]));
            }
            set {
                this["CoalitionsJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsShowingCoalitionsColumn {
            get {
                return ((bool)(this["IsShowingCoalitionsColumn"]));
            }
            set {
                this["IsShowingCoalitionsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("530, 540")]
        public global::System.Drawing.Size DScanLocatorSize {
            get {
                return ((global::System.Drawing.Size)(this["DScanLocatorSize"]));
            }
            set {
                this["DScanLocatorSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 200")]
        public global::System.Drawing.Point DScanLocatorPosition {
            get {
                return ((global::System.Drawing.Point)(this["DScanLocatorPosition"]));
            }
            set {
                this["DScanLocatorPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("650, 650")]
        public global::System.Drawing.Size POSMapperSize {
            get {
                return ((global::System.Drawing.Size)(this["POSMapperSize"]));
            }
            set {
                this["POSMapperSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 200")]
        public global::System.Drawing.Point POSMapperPosition {
            get {
                return ((global::System.Drawing.Point)(this["POSMapperPosition"]));
            }
            set {
                this["POSMapperPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350, 350")]
        public global::System.Drawing.Size ProbeScanSize {
            get {
                return ((global::System.Drawing.Size)(this["ProbeScanSize"]));
            }
            set {
                this["ProbeScanSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 200")]
        public global::System.Drawing.Point ProbeScanPosition {
            get {
                return ((global::System.Drawing.Point)(this["ProbeScanPosition"]));
            }
            set {
                this["ProbeScanPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024, 800")]
        public global::System.Drawing.Size MapSize {
            get {
                return ((global::System.Drawing.Size)(this["MapSize"]));
            }
            set {
                this["MapSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 200")]
        public global::System.Drawing.Point MapPosition {
            get {
                return ((global::System.Drawing.Point)(this["MapPosition"]));
            }
            set {
                this["MapPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MapDockLayout {
            get {
                return ((string)(this["MapDockLayout"]));
            }
            set {
                this["MapDockLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Role")]
        public string DScanShipAggregatorGroupBy {
            get {
                return ((string)(this["DScanShipAggregatorGroupBy"]));
            }
            set {
                this["DScanShipAggregatorGroupBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastSavedDockVersion {
            get {
                return ((int)(this["LastSavedDockVersion"]));
            }
            set {
                this["LastSavedDockVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection PositionTrackingCharacters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PositionTrackingCharacters"]));
            }
            set {
                this["PositionTrackingCharacters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShortcutToggleMinimizeAll {
            get {
                return ((string)(this["ShortcutToggleMinimizeAll"]));
            }
            set {
                this["ShortcutToggleMinimizeAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{}")]
        public string LastCharacterPositionsJson {
            get {
                return ((string)(this["LastCharacterPositionsJson"]));
            }
            set {
                this["LastCharacterPositionsJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int RouteFinderSecurityPenalty {
            get {
                return ((int)(this["RouteFinderSecurityPenalty"]));
            }
            set {
                this["RouteFinderSecurityPenalty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shortest")]
        public string RouteFinderRouteType {
            get {
                return ((string)(this["RouteFinderRouteType"]));
            }
            set {
                this["RouteFinderRouteType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MapRangeAroundRoute {
            get {
                return ((int)(this["MapRangeAroundRoute"]));
            }
            set {
                this["MapRangeAroundRoute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RouteFinderIsIgnoringWormholes {
            get {
                return ((bool)(this["RouteFinderIsIgnoringWormholes"]));
            }
            set {
                this["RouteFinderIsIgnoringWormholes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public double WindowBackgroundTransparencyLevel {
            get {
                return ((double)(this["WindowBackgroundTransparencyLevel"]));
            }
            set {
                this["WindowBackgroundTransparencyLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShortcutQuickAction {
            get {
                return ((string)(this["ShortcutQuickAction"]));
            }
            set {
                this["ShortcutQuickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AreVoiceCommandsEnabled {
            get {
                return ((bool)(this["AreVoiceCommandsEnabled"]));
            }
            set {
                this["AreVoiceCommandsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("toggle")]
        public string VoiceCommandToggleMinimze {
            get {
                return ((string)(this["VoiceCommandToggleMinimze"]));
            }
            set {
                this["VoiceCommandToggleMinimze"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P L H")]
        public string VoiceCommandQuickAction {
            get {
                return ((string)(this["VoiceCommandQuickAction"]));
            }
            set {
                this["VoiceCommandQuickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState MapWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["MapWindowState"]));
            }
            set {
                this["MapWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AbsolutePvpOrPveActivityIndexCalculator")]
        public string MapInnerCircleColorType {
            get {
                return ((string)(this["MapInnerCircleColorType"]));
            }
            set {
                this["MapInnerCircleColorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AbsolutePodKillActivityIndexCalculator")]
        public string MapCircleBorderType {
            get {
                return ((string)(this["MapCircleBorderType"]));
            }
            set {
                this["MapCircleBorderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("StationTriStateCalculator")]
        public string MapCircleMarkerType {
            get {
                return ((string)(this["MapCircleMarkerType"]));
            }
            set {
                this["MapCircleMarkerType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SingleHueRedPalette")]
        public string MapInnerCirclePalette {
            get {
                return ((string)(this["MapInnerCirclePalette"]));
            }
            set {
                this["MapInnerCirclePalette"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TransparentToRedPalette")]
        public string MapCircleBorderPalette {
            get {
                return ((string)(this["MapCircleBorderPalette"]));
            }
            set {
                this["MapCircleBorderPalette"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF800080")]
        public global::System.Windows.Media.Color MapTriStateColor {
            get {
                return ((global::System.Windows.Media.Color)(this["MapTriStateColor"]));
            }
            set {
                this["MapTriStateColor"] = value;
            }
        }
    }
}
