// <auto-generated />
namespace EVE_Killboard_Analyser.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PositionToVictim : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PositionToVictim));
        
        string IMigrationMetadata.Id
        {
            get { return "201512011343432_PositionToVictim"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
